// https://www.fhwa.dot.gov/tpm/guidance/pm3_hpms.pdf

module.exports = {
  lottr_amp: 'LOTTR_AMP',
  tt_amp50pct: 'TT_AMP50PCT',
  tt_amp80pct: 'TT_AMP80PCT',
  lottr_midd: 'LOTTR_MIDD',
  tt_midd50pct: 'TT_MIDD50PCT',
  tt_midd80pct: 'TT_MIDD80PCT',
  lottr_pmp: 'LOTTR_PMP',
  tt_pmp50pct: 'TT_PMP50PCT',
  tt_pmp80pct: 'TT_PMP80PCT',
  lottr_we: 'LOTTR_WE',
  tt_we50pct: 'TT_WE50PCT',
  tt_we80pct: 'TT_WE80PCT',
  tttr_amp: 'TTTR_AMP',
  ttt_amp50pct: 'TTT_AMP50PCT',
  ttt_amp95pct: 'TTT_AMP95PCT',
  tttr_midd: 'TTTR_MIDD',
  ttt_midd50pct: 'TTT_MIDD50PCT',
  ttt_midd95pct: 'TTT_MIDD95PCT',
  tttr_pmp: 'TTTR_PMP',
  ttt_pmp50pct: 'TTT_PMP50PCT',
  ttt_pmp95pct: 'TTT_PMP95PCT',
  tttr_ovn: 'TTTR_OVN',
  ttt_ovn50pct: 'TTT_OVN50PCT',
  ttt_ovn95pct: 'TTT_OVN95PCT',
  tttr_we: 'TTTR_WE',
  ttt_we50pct: 'TTT_WE50PCT',
  ttt_we95pct: 'TTT_WE95PCT'
};
