module.exports = [
  'tmc',
  'faciltype',
  'aadt',
  'aadt_singl',
  'aadt_combi',
  'length',
  'direction',
  'avg_speedlimit',
  'congestion_level',
  'directionality',
  'avg_vehicle_occupancy',
  'f_system',
  'nhs',
  'nhs_pct',
  'is_interstate',
  'is_controlled_access',
  'mpo_code AS mpo',
  'ua_code',
  'ua_code AS ua',
  'county_code AS county',
  'state_code',
  'state_code AS state',
  'bounding_box'
];
