BEGIN;

ALTER TABLE geolevel_pm3
  ADD COLUMN IF NOT EXISTS td_0  NUMERIC,
  ADD COLUMN IF NOT EXISTS td_1  NUMERIC,
  ADD COLUMN IF NOT EXISTS td_2  NUMERIC,
  ADD COLUMN IF NOT EXISTS td_3  NUMERIC,
  ADD COLUMN IF NOT EXISTS td_4  NUMERIC,
  ADD COLUMN IF NOT EXISTS td_5  NUMERIC,
  ADD COLUMN IF NOT EXISTS td_6  NUMERIC,
  ADD COLUMN IF NOT EXISTS td_7  NUMERIC,
  ADD COLUMN IF NOT EXISTS td_8  NUMERIC,
  ADD COLUMN IF NOT EXISTS td_9  NUMERIC,
  ADD COLUMN IF NOT EXISTS td_10 NUMERIC,
  ADD COLUMN IF NOT EXISTS td_11 NUMERIC,
  ADD COLUMN IF NOT EXISTS td_12 NUMERIC,

  ADD COLUMN IF NOT EXISTS tpd_0  NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_1  NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_2  NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_3  NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_4  NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_5  NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_6  NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_7  NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_8  NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_9  NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_10 NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_11 NUMERIC,
  ADD COLUMN IF NOT EXISTS tpd_12 NUMERIC,

  ADD COLUMN IF NOT EXISTS tvd_0  NUMERIC
  ADD COLUMN IF NOT EXISTS tvd_1  NUMERIC,
  ADD COLUMN IF NOT EXISTS tvd_2  NUMERIC,
  ADD COLUMN IF NOT EXISTS tvd_3  NUMERIC,
  ADD COLUMN IF NOT EXISTS tvd_4  NUMERIC,
  ADD COLUMN IF NOT EXISTS tvd_5  NUMERIC,
  ADD COLUMN IF NOT EXISTS tvd_6  NUMERIC,
  ADD COLUMN IF NOT EXISTS tvd_7  NUMERIC,
  ADD COLUMN IF NOT EXISTS tvd_8  NUMERIC,
  ADD COLUMN IF NOT EXISTS tvd_9  NUMERIC,
  ADD COLUMN IF NOT EXISTS tvd_10 NUMERIC,
  ADD COLUMN IF NOT EXISTS tvd_11 NUMERIC,
  ADD COLUMN IF NOT EXISTS tvd_12 NUMERIC
;

COMMIT;
